### ISSUE TITLE
demo无法正常工作

### ISSUE THREAD

**Issue by soooldier** [goosman-lei/php-ckcr#1]
hi，您好。现在项目正好需要类似功能，但是测试本项目demo中发现了一些问题，比如修改preDefined段中show里面的id字段为str，运行之后并未发现对id参数string化

**Comment by goosman-lei** [comment]
抱歉, 是一个Bug, 已经Fix了.

**Comment by goosman-lei** [comment]
另外, 如果感兴趣可以看看我新写的框架. [ice框架](https://github.com/goosman-lei/ice)
这个框架中的Filter模块就是php-ckcr, 
相比目前这个版本, 对编译过程做了一些优化处理, 另外, 对preDefined的东西, 从概念和语法支持上也更加明确, 作为ref(引用)支持

**Comment by soooldier** [comment]
好的，非常感谢！
